server:
  port: 8070
  servlet:
    context-path: /dfyoo
spring:
  session:
    store-type: none
dfyoo:
  baseurl: https://doptest-api.dfyoo.com
  acctid: 100012
  ticket:
    apikey: tickettest
    secretkey: aaaaaaaa
    paytype: 1
  public:
    apikey: publictest
    secretkey: aaaaaaaa